name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup and Check
        run: ./ci.sh
